model: SEResNet34
encoder_type: ASP
trainfunc: aamsoftmax
nClasses: 1015
batch_size: 16
max_seg_per_spk: 1000
augment: True
max_epoch: 2
save_path: output/ResNetSE34V2_SAP_AAM
train_list: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/metadata/train/training_metadata.txt
train_path: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1
test_list: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/metadata/test/sample_test_pairs.txt
test_path: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/test/sv_vlsp_2021/public_test/competition_public_test
musan_path: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/musan_augment
rir_path: /home/dungnasa/Desktop/Coding/Python/Deep-Learning-Project-2022-1/data/rirs_noises
output_path: output/submission/t1/private_test